const helpers = require('./helpers.js');

const data = helpers.createItem({
  key: '7HLUVS5G',
  version: 14873,
  itemType: 'journalArticle',
  title:
    '(Y<sub>0.25</sub>Yb<sub>0.25</sub>Er<sub>0.25</sub>Lu<sub>0.25</sub>)<sub>2</sub>(Zr<sub>0.5</sub>Hf<sub>0.5</sub>)<sub>2</sub>O<sub>7</sub>: a defective fluorite structured high entropy ceramic with low thermal conductivity and close thermal expansion coefficient to Al<sub>2</sub>O<sub>3</sub>',
  creators: [
    { creatorType: 'author', firstName: 'Zifan', lastName: 'Zhao' },
    { creatorType: 'author', firstName: 'Heng', lastName: 'Chen' },
    { creatorType: 'author', firstName: 'Huimin', lastName: 'Xiang' },
    { creatorType: 'author', firstName: 'Fu-Zhi', lastName: 'Dai' },
    { creatorType: 'author', firstName: 'Xiaohui', lastName: 'Wang' },
    { creatorType: 'author', firstName: 'Wei', lastName: 'Xu' },
    { creatorType: 'author', firstName: 'Kuang', lastName: 'Sun' },
    { creatorType: 'author', firstName: 'Zhijian', lastName: 'Peng' },
    { creatorType: 'author', firstName: 'Yanchun', lastName: 'Zhou' },
  ],
  abstractNote: '',
  publicationTitle: 'Journal of Materials Science & Technology',
  volume: '39',
  issue: '',
  pages: '167-172',
  date: '02/2020',
  series: '',
  seriesTitle: '',
  seriesText: '',
  journalAbbreviation: 'Journal of Materials Science & Technology',
  language: 'en',
  DOI: '10.1016/j.jmst.2019.08.018',
  ISSN: '10050302',
  shortTitle: '(Y0.25Yb0.25Er0.25Lu0.25)2(Zr0.5Hf0.5)2O7',
  url: 'https://linkinghub.elsevier.com/retrieve/pii/S1005030219303329',
  accessDate: '2024-11-21T17:07:44Z',
  archive: '',
  archiveLocation: '',
  libraryCatalog: 'DOI.org (Crossref)',
  callNumber: '',
  rights: '',
  extra: 'GSCC: 0000071',
  tags: [],
  collections: ['27YH8FR3'],
  relations: {},
  dateAdded: '2024-11-21T17:07:44Z',
  dateModified: '2024-12-11T17:57:43Z',
});

module.exports = { data };
