const getField = function (key) {
  return this[key];
};

const getCreators = function () {
  return this.creators;
};

const data = [
  {
    key: 'LHX8PRC3',
    version: 246,
    itemType: 'journalArticle',
    title:
      'From transactional to transformational leadership: Learning to share the vision',
    date: 'December 1, 1990',
    language: 'en',
    shortTitle: 'From transactional to transformational leadership',
    libraryCatalog: 'ScienceDirect',
    url: 'https://www.sciencedirect.com/science/article/pii/009026169090061S',
    accessDate: '2021-09-22T20:55:33Z',
    extra: '',
    volume: '18',
    pages: '19-31',
    publicationTitle: 'Organizational Dynamics',
    DOI: '10.1016/0090-2616(90)90061-S',
    issue: '3',
    journalAbbreviation: 'Organizational Dynamics',
    ISSN: '0090-2616',
    creators: [
      {
        firstName: 'Bernard M.',
        lastName: 'Bass',
        creatorType: 'author',
      },
    ],
    tags: [],
    collections: ['I39PBJTI'],
    relations: {},
    dateAdded: '2021-09-22T20:55:33Z',
    dateModified: '2021-09-29T00:42:27Z',
    getField,
    getCreators,
  },
  {
    key: 'KAZLLGBU',
    version: 247,
    itemType: 'journalArticle',
    title:
      'Predicting unit performance by assessing transformational and transactional leadership.',
    date: '2003',
    language: 'en',
    libraryCatalog: 'DOI.org (Crossref)',
    url: 'http://doi.apa.org/getdoi.cfm?doi=10.1037/0021-9010.88.2.207',
    accessDate: '2021-09-24T00:41:46Z',
    extra: 'GSCC: 0005185',
    volume: '88',
    pages: '207-218',
    publicationTitle: 'Journal of Applied Psychology',
    DOI: '10.1037/0021-9010.88.2.207',
    issue: '2',
    journalAbbreviation: 'Journal of Applied Psychology',
    ISSN: '1939-1854, 0021-9010',
    creators: [
      {
        firstName: 'Bernard M.',
        lastName: 'Bass',
        creatorType: 'author',
      },
      {
        firstName: 'Bruce J.',
        lastName: 'Avolio',
        creatorType: 'author',
      },
      {
        firstName: 'Dong I.',
        lastName: 'Jung',
        creatorType: 'author',
      },
      {
        firstName: 'Yair',
        lastName: 'Berson',
        creatorType: 'author',
      },
    ],
    tags: [],
    collections: ['I39PBJTI'],
    relations: {},
    dateAdded: '2021-09-24T00:41:46Z',
    dateModified: '2021-09-29T00:41:58Z',
    getField,
    getCreators,
  },
  {
    key: 'YTXC4I3K',
    version: 247,
    itemType: 'journalArticle',
    title:
      'Personality and Transformational and Transactional Leadership: A Meta-Analysis',
    date: '2004',
    language: 'en',
    libraryCatalog: 'Zotero',
    extra: '',
    volume: '89',
    pages: '901-910',
    publicationTitle: 'Journal of Applied Psychology',
    DOI: '10.1037/0021-9010.89.5.901',
    issue: '5',
    ISSN: '0021-9010',
    creators: [
      {
        firstName: 'Joyce E',
        lastName: 'Bono',
        creatorType: 'author',
      },
      {
        firstName: 'Timothy A',
        lastName: 'Judge',
        creatorType: 'author',
      },
    ],
    tags: [],
    collections: ['I39PBJTI'],
    relations: {},
    dateAdded: '2021-09-24T00:42:25Z',
    dateModified: '2021-09-29T00:42:02Z',
    getField,
    getCreators,
  },
  {
    key: 'VMNJLHPI',
    version: 247,
    itemType: 'journalArticle',
    title:
      'Situational, Transformational, and Transactional Leadership and Leadership Development',
    abstractNote:
      'In order to advance our knowledge of leadership, it is necessary to understand where the study of leadership has been. McCleskey (2014) argued that the study of leadership spans more than 100 years. This manuscript describes three seminal leadership theories and their development. Analysis of a sampling of recent articles in each theory is included. The manuscript also discusses the concept of leadership development in light of those three seminal theories and offers suggestions for moving forward both the academic study of leadership and the practical application of research findings on the field.',
    date: '2014',
    language: 'en',
    libraryCatalog: 'Zotero',
    extra: '',
    volume: '5',
    pages: '14',
    publicationTitle: 'Journal of Business Studies Quarterly',
    issue: '4',
    ISSN: '2152-1034',
    creators: [
      {
        firstName: 'Jim Allen',
        lastName: 'McCleskey',
        creatorType: 'author',
      },
    ],
    tags: [],
    collections: ['I39PBJTI'],
    relations: {},
    dateAdded: '2021-09-24T00:42:01Z',
    dateModified: '2021-09-29T00:42:05Z',
    getField,
    getCreators,
  },
  {
    key: '3ZBCBKUH',
    version: 246,
    itemType: 'journalArticle',
    title:
      'Potential Biases in Leadership Measures: How Prototypes, Leniency, and General Satisfaction Relate to Ratings and Rankings of Transformational and Transactional Leadership Constructs',
    abstractNote:
      "Eighty-seven respondents completed either a graphic rating or a forced ranking questionnaire describing their immediate superior. Five leadership scales were embedded in each questionnaire. Three represented transformational leadership constructs (charismatic leadership, individualized consideration, and intellectual stimulation); two reflected transactional leadership constructs (contingent reward and management-by-exception). Appended to each questionnaire were five additional scales. The items constituting these scales measured two outcomes-satisfaction with the leader and effectiveness of the leader. The remaining scales measured each participant's leadership prototype, the participant's tendency to be lenient in his/her ratings, and a general measure of satisfaction. As expected, the intercorrelations among the factor scores representing the transformational and transactional leadership constructs were reduced substantially by using the forced rankings as compared with the graphic ratings. Also, the magnitude of the relationships among leadership and outcome factor scores was reduced, on average, when using the forced rankings. Prototypicality factor scores were more highly correlated with factor scores reflecting transformational than were factor scores portraying transactional leadership. The tendency of participants to be more or less lenient in their ratings or rankings and their general level of satisfaction were of little or no consequence to the intercorrelations among the leadership and outcome factor scales.",
    date: 'September 1, 1989',
    url: 'https://doi.org/10.1177/001316448904900302',
    accessDate: '2021-09-22',
    extra: 'GSCC: 0000505 \nPublisher: SAGE Publications Inc',
    volume: '49',
    pages: '509-527',
    publicationTitle: 'Educational and Psychological Measurement',
    DOI: '10.1177/001316448904900302',
    issue: '3',
    journalAbbreviation: 'Educational and Psychological Measurement',
    ISSN: '0013-1644',
    creators: [
      {
        firstName: 'Bernard M.',
        lastName: 'Bass',
        creatorType: 'author',
      },
      {
        firstName: 'Bruce J.',
        lastName: 'Avolio',
        creatorType: 'author',
      },
    ],
    tags: [],
    collections: ['I39PBJTI'],
    relations: {},
    dateAdded: '2021-09-22T20:25:22Z',
    dateModified: '2021-09-29T00:41:26Z',
    getField,
    getCreators,
  },
];

module.exports = data;
